### ISSUE TITLE
How to run and integrate to Home Assistant

### ISSUE THREAD

**Issue by pornstrup** [AdamStrojek/etrv2mqtt#1]
How do I run the script and integrate it to Home Assistant? Ive followed your install-instructions and installed on a raspberry pi (stretch) but cannot get it working. Do I need MQTT installed in the RaspPi?  I´ve got Home Assistant running on a VMWare in a docker container on a PC.

**Comment by AdamStrojek** [comment]
Unfortunately this application is still in early stage of development. Currently I'm focusing on developing library that will allow on further integrations. Until I finish that I will not start implementing MQTT functionality or Home Assistant integration. Currently I'm trying to implement encryption and decryption method that is used in communication. I will update README file to not confuse people.

Installation instruction for now is mostly targeted at developers who want to help me improve application. As I mentioned before now biggest problem is to decode messages. As far as I had researched this topic it looks like modified version of xxtea algorithm. Also data are sent in big endian.

**Comment by pornstrup** [comment]
OK thanks for the quick reply. Wish I could help you out, but not much of a coder.
